/* Copyright (c) 2018 Salesforce
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
 */

package hmiddleware

import (
	"log"
	"net/http"
	"os"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	tags "github.com/grpc-ecosystem/go-grpc-middleware/tags"
	"github.com/sirupsen/logrus"
)

func ExampleCORS() {
	r := chi.NewRouter()
	r.Use(CORS)

	// OR

	var h http.Handler

	if err := http.ListenAndServe(":"+os.Getenv("PORT"), CORS(h)); err != nil {
		log.Fatal(err)
	}
}

func ExampleDisableKeepalive() {
	r := chi.NewRouter()
	r.Use(DisableKeepalive)

	// OR

	var h http.Handler

	if err := http.ListenAndServe(":"+os.Getenv("PORT"), DisableKeepalive(h)); err != nil {
		log.Fatal(err)
	}
}

func ExampleEnsureTLS() {
	r := chi.NewRouter()
	r.Use(EnsureTLS)

	// OR

	var h http.Handler

	if err := http.ListenAndServe(":"+os.Getenv("PORT"), EnsureTLS(h)); err != nil {
		log.Fatal(err)
	}
}

func ExampleTags() {
	r := chi.NewRouter()
	r.Use(Tags)
	logger := logrus.StandardLogger()
	l := &StructuredLogger{
		Logger: logger,
	}
	r.Use(middleware.RequestLogger(l))

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		// foo=bar will show up in the HTTP request logs generated by StructuredLogger
		tags.Extract(r.Context()).Set("foo", "bar")
		w.WriteHeader(http.StatusOK)
	})

}
