name: CI

on: [ push ]

jobs:
  ci:
    runs-on: pub-hk-ubuntu-24.04-ip
    env:
      GOMARKDOC_OPTS: -c
    strategy:
      matrix:
        target: [ test, lint, docs ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "./go.mod"
        check-latest: true
    - name: run ${{ matrix.target }}
      run: make ${{ matrix.target }}
