name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.31.0
          args: --timeout 5m
      - name: Run Test
        run: go test -race -v ./...
