name: ci

on: [ push ]

jobs:
  ci:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        target: [ test, lint ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: run ${{ matrix.target }}
      run: make ${{ matrix.target }}
