name: CI

on: [ push ]

jobs:
  ci:
    runs-on: pub-hk-ubuntu-24.04-ip
    env:
      GOMARKDOC_OPTS: -c
    strategy:
      matrix:
        target: [ test, lint, docs ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: run ${{ matrix.target }}
      run: make ${{ matrix.target }}
